version: '3'

services:

  database:
    image: postgres:14
    restart: unless-stopped
    # Override the image command to enable statement logging, output to the Docker log
    # and enable pg_stat_statements, which is disabled by default
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr", "-c", "shared_preload_libraries=pg_stat_statements", "-c", "pg_stat_statements.track=all"]
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: pguser
      POSTGRES_DB: db
    ports:
      # Postgresql
      - "5432"
